### PR TITLE
XS✔ ◾ Updated do-you-create-your-own-process-template-to-fit-into-your-envi…

### PR DESCRIPTION
**Pull request by tiagov8**
…ronment

- Removed non-standard greybox
- Improved figures
- Added link to product

### CODE REVIEW

**Comment by tiagov8** [comment]
Hi @JackDevAU 

- [ ] 1. Can you check if the reference to "TFS" in this rule can be updated to "Azure DevOps" ? And action if yes

**Comment by tiagov8** [comment]
Hey @GordonBeeming 

I think this one might be related to the PR you're working on: https://github.com/SSWConsulting/SSW.Rules.Content/pull/7082

Can you check my comment to @JackDevAU above?

Cheers,

**Comment by GordonBeeming** [comment]
Howzit @tiagov8 @JackDevAU 

https://www.ssw.com.au/rules/do-you-create-your-own-process-template-to-fit-into-your-environment/

The UI from the rule suggests this is very old. 

If we do feel those field are valuable still (I don't see them in our current process), then I'd recommend we create a new rule based off the current Azure DevOps functionality to change process templates and then archive this rule as being super-seeded by the newer functionality.

**Comment by tiagov8** [comment]
Hi @GordonBeeming 

>  I'd recommend we create a new rule based off the current Azure DevOps functionality to change process templates and then archive this rule as being super-seeded by the newer functionality.

- [ ] 1. Please approve this PR (rule content is outdated but it has some improvements)
- [ ] 2. Create an Issue to create that new rule on Azure DevOps (mention to archive the old one)

**Review by GordonBeeming — APPROVED** [review]
LGTM... However we should look at archiving as the specific content is no longer relevant

**Review by UlyssesMaclaren — APPROVED** [review]

**Pull request merged**
