### PR TITLE
Update Rule “disable-users-rather-than-deleting-for-better-crm-reporting/rule”

### PR DESCRIPTION
**Pull request by chrisschultzssw**
Automatically generated by Netlify CMS

### CODE REVIEW

**Review by leahy268 — CHANGES_REQUESTED** [review]
Read the below:

This in turn make reporting on a user that has returned more difficult. So to get around this it is disabling and moving the user to a "Disable Users" Organizational Unit (OU) in AD is much easier, so that in the event that the return, the AD and CRM user can just be re-enabled.

It doesn't make sense.

**Review by adamcogan — APPROVED** [review]

**Comment by chrisschultzssw** [comment]
> Read the below:
> 
> This in turn make reporting on a user that has returned more difficult. So to get around this it is disabling and moving the user to a "Disable Users" Organizational Unit (OU) in AD is much easier, so that in the event that the return, the AD and CRM user can just be re-enabled.
> 
> It doesn't make sense.

Yeah wow. I didn't write that... but have now re-worded it (and some of the rest of the rule) to make sense/read better.

**Review by adamcogan — APPROVED** [review]

**Review by leahy268 — APPROVED** [review]
Great, much better

**Review by leahy268 — COMMENTED** [review]
..

**Pull request merged**
