### PR TITLE
Create Rule “net-maui-for-xplat-ui/rule”

### PR DESCRIPTION
**Pull request by matt-goldman**
Automatically generated by Netlify CMS

### CODE REVIEW

**Review by tiagov8 — CHANGES_REQUESTED** [review]
Hey @matt-goldman 

See https://ssw.com.au/rules/images-should-be-hosted-internally/

1. Can you follow this rule for all images?

See https://github.com/SSWConsulting/SSW.Rules.Content/wiki/How-to-Add-and-Edit-Categories-and-Top-Categories#edit-a-category

2. Can you also add this new rule to a relevant category

**Comment by matt-goldman** [comment]
Hi @tiagov8 

Thanks for the feedback, sorry for the delay I've been on client work and am only just getting back to this now.

> See https://ssw.com.au/rules/images-should-be-hosted-internally/
> 
> 1. Can you follow this rule for all images?

Thanks - I hadn't seen this rule. To create this new rule, I followed the tutorial in the wiki: https://github.com/SSWConsulting/SSW.Rules.Content/wiki/How-to-Create-Rules.  It doesn't follow the internal images rule, it says to include it with the rest of the content (this PR). See: https://github.com/SSWConsulting/SSW.Rules.Content/wiki/How-to-Add-an-Image.

1. Does this rule apply to Rules content, or should that be for the website?
2. Should the wiki be updated?
3. Can you give me guidance on how and where to store images internally in order to comply with the rule?

> See https://github.com/SSWConsulting/SSW.Rules.Content/wiki/How-to-Add-and-Edit-Categories-and-Top-Categories#edit-a-category
> 
> 2. Can you also add this new rule to a relevant category

Done.

**Comment by tiagov8** [comment]
Hi @matt-goldman 

> 1. Does this rule apply to Rules content, or should that be for the website?
The rule applies to any web content - do not link to images that are hosted in a server you don't have control over
I don't remember exactly but I think I saw some images linked from a separated external website on my 1st review?

> 2. Should the wiki be updated?
From what I see here no change is needed https://github.com/SSWConsulting/SSW.Rules.Content/wiki/How-to-Add-an-Image 

> 3. Can you give me guidance on how and where to store images internally in order to comply with the rule?
As per then link above, SSW.Rules are in GitHub and the content images for each rule are stored in the same folder as the .md file.

**Comment by tiagov8** [comment]
Hi @matt-goldman

> 1. Does this rule apply to Rules content, or should that be for the website?

The rule applies to any web content - do not link to images that are hosted in a server you don't have control over
I sent that task because in your rule content I see the below image, which is hosted by Apple:

```
https://developer.apple.com/swift/resources/images/tutorial-develop-apps-ios_2x.webp
```

> 2. Should the wiki be updated?

From what I see here no change is needed https://github.com/SSWConsulting/SSW.Rules.Content/wiki/How-to-Add-an-Image

> 3. Can you give me guidance on how and where to store images internally in order to comply with the rule?

As per then link above, SSW.Rules are in GitHub and the content images for each rule are stored in the same folder as the .md file.

**Comment by matt-goldman** [comment]
Hi @tiagov8 

Understood, I get it now. I was confused because I created this rule using Netlify and I thought all the images had uploaded. I thought you were referring to the images in GitHub so I didn't understand where else to put them.

I can see now that a few of them are links. I've fixed this up now.

**Review by tiagov8 — APPROVED** [review]

**Pull request merged**
