### PR TITLE
XS✔ ◾ from x to y - add green to represent added text

### PR DESCRIPTION
**Pull request by bradystroud**
**Tip: Use [SSW Rule Writer GPT](https://chat.openai.com/g/g-cOvrRzEnU-ssw-rules-writer) for help with writing rules 🤖**
>
> 1. What triggered this change? (PBI link, Email Subject, conversation + reason, etc)

I have been doing this and I think it is better.
@tiagov8 What do you think of this change?

> 2. What was changed?

✏️

> 3. Did you do pair or mob programming (list names)?

✏️

### CODE REVIEW

**Comment by tiagov8** [comment]
> @tiagov8 What do you think of this change?

I agree it **looks** better, but in practical terms I don't think it makes much difference.

I believe using green was already considered for the rule, but we chose to keep yellow only to keep things simpler. 

I don't mind changing it, but I would probably get more people to add their thoughts...

Few things:

- Many times we will have both edits and adds to a sentence, so changing the highlight color for each piece of text may be annoying
- We know the highlight in yellow is commonly available in different software, but green is a little less supported
- We have a SugarLearning item that needs to be updated if something changes with the rule https://my.sugarlearning.com/SSW/items/8148/ssws-culture-of-consistency-and-change

**Comment by uly1** [comment]
FYI I dont like it... extra complication with very little added benefit. at the moment yellow means new, red means gone... simple!

**Comment by tiagov8** [comment]
Hey @bradystroud 

Since @uly1 and I agreed yellow is enough, I guess we can close this PR?

**Comment by bradystroud** [comment]
@tiagov8 @uly1 

Thanks!

For the record, I think red green yellow is clearer, like a git diff, but happy to stick with the current system that works 🙂

**Pull request closed without merging**
