### PR TITLE
XS✔ ◾ Made link a code + small improvements "sprint-forecast/"

### PR DESCRIPTION
**Pull request by tiagov8**
❌ **Add a description.**

### CODE REVIEW

**Comment by GordonBeeming** [comment]
Howzit @tiagov8 

Please could you add some more **context to your PR description**. It's important to know why changes were made and who was involved in the conversations for follow-up changes later on.

Some examples of what would be helpful are below:

**As per my conversation with...**

As per my conversation with Gordon, these rules have no category and should be added to the rules to the Rules for Better GitHub category 

**Based on email thread...**

Based on email thread:
**From:** Gordon Beeming [SSW]
**Sent:** Wednesday, August 16, 2023 11:48 PM 
**Subject:** RE: Secrets and passwords storage for SSW Projects 🔑

**I noticed that...**

I noticed that the formatting was out for this rule, so I fixed it.

**Comment by tiagov8** [comment]
Hi @GordonBeeming 

The title says it all. 
The tag "rubber stamp" shows the changes are simple and don't require thorough review

See the "tip" here https://www.ssw.com.au/rules/write-a-good-pull-request/#2-write-a-concise-and-descriptive-body

Read https://www.ssw.com.au/rules/rubber-stamp-prs

**Review by bradystroud — APPROVED** [review]

**Comment by bradystroud** [comment]
Approved because rubber stamp means simple change

**Comment by GordonBeeming** [comment]
Howzit @tiagov8 

I'm less concerned here with what is in the change and more about what triggered the change to be made

FYI: The tip in the rule has been updated to reflect this now as well

https://www.ssw.com.au/rules/write-a-good-pull-request/#2-write-a-concise-and-descriptive-body

I'm reviewing the rubber stamp rule now as blindly approving PRs doesn't sit well with me

cc: @matt-goldman @wicksipedia

**Comment by tiagov8** [comment]
@GordonBeeming 

> more about what triggered the change to be made

This is a common scenario to me: https://www.ssw.com.au/rules/fix-small-web-errors/

--

I understand your developer perspective, but note the rule on rubber stamp never says "blindly". The main goal with the 3 links I mentioned above is to make small content changes and fixes more efficient and less bureaucratic. If you disagree with the rules, we can discuss further.

FYI - PRs like this have been reviewed and approved by me and Brady (and others) dozens of times and I never experienced any issues caused by them. It's crucial to distinguish between **content** and **code** changes. The 1st will not break things, the latter might. The review process shouldn't be the same IMO.

**Comment by GordonBeeming** [comment]
@tiagov8 I tried to call but you were not available

> This is a common scenario to me

All I'm asking is if you've noticed something, say  "I noticed that xxx". This way, it's clear to anyone reviewing where the change came from. There could be a long mail thread around a change (even if it looks simple), and nobody knows that's the case because there's no information in the PR. 

Adding a screenshot of what the issue is that you found would be helpful to give more context to reviewers

> but note the rule on rubber stamp never says "blindly"

image
**Figure: The label reads anyone is allowed to approve without looking**, the same is true for the screenshot on the rule

> If you disagree with the rules, we can discuss further

Currently, I do, see mail subject: SSW Rule Review - Do you have a "rubber stamp" approval method for PRs?

> FYI - PRs like this have been reviewed and approved by me and Brady (and others) dozens of times, and I never experienced any issues caused by them. It's crucial to distinguish between content and code changes. The 1st will not break things, the latter might. The review process shouldn't be the same IMO

Again, all I'm asking for here is what triggered the task. This way I'm changing something that has recently changed I know where to find more information about why changes were made. \
Even for content, it's important to know why content is changing, and who is in the loop for it being changed

**Comment by tiagov8** [comment]
Hey @GordonBeeming 

> Figure: The label reads anyone is allowed to approve without looking, the same is true for the screenshot on the rule

I didn't notice that and you are correct. I've updated the label description + image in the rule: https://github.com/SSWConsulting/SSW.Rules.Content/pull/6862

**Pull request merged**
