### PR TITLE
Created "Do you know how test MAUI apps?" rule

### PR DESCRIPTION
**Pull request by vladislav-kir**
Created a new Rule "Do you test .NET MAUI apps on different devices?".

Added it to following categories:
- Rules to Better .NET MAUI (was Xamarin)
- Rules to Better Apps (mobile)

### CODE REVIEW

**Review by matt-goldman — COMMENTED** [review]
This is an awesome rule! I would suggest one conceptual change though.

If I were reading a rule titled 'Do you know how to test MAUI apps?', I would expect something covering repl and automation IDs. I think this rule is more about testing cross-platform apps on different devices, so you could update the title to reflect that, and you could also make it more broad (i.e. mobile apps rather than .NET MAUI specifically).

One last thing - Microsoft get grumpy if you call it MAUI and not .NET MAUI (probably because there was already a UI project called MAUI...)

**Comment by bradystroud** [comment]
@matt-goldman @vladislav-kir 

Usually when we give multiple options, one of them is recommened. Should we recommend one here?

as per https://www.ssw.com.au/rules/do-you-manage-up/#multiple-options

**Comment by vladislav-kir** [comment]
@matt-goldman 

I renamed the rule to "Do you test .NET MAUI apps on different devices?" to better represent the point of this rule.
Although the bulk is content can be apply for other mobile dev frameworks, the focus of the rule is supposed to be for the MAUI, as per 📱 Mobile Apps - SSW iOS and Android devices available for testing email chain.

Also, I refer to MAUI as .NET MAUI where appropriate, and I remember to do so in the future :)

@bradystroud

I recommended the Option 3: Use real devices, which then links to the Mobile Device Policy rule.

Regarding the Check-Images action breaking... Do I need to fix something, or is that expected?

**Comment by bradystroud** [comment]
> Regarding the Check-Images action breaking... Do I need to fix something, or is that expected?

I'll get @BrookJeynes to take a look

**Review by bradystroud — APPROVED** [review]

**Pull request merged**
