### PR TITLE
Fix acknowledgement on “dotnet-upgrade-for-complex-projects/rule”

### PR DESCRIPTION
**Pull request by zacharykeeping**
Fix acknowledgement pointing to Tom B instead of Tom I.

### CODE REVIEW

**Review by tiagov8 — CHANGES_REQUESTED** [review]
Hey @zacharykeeping 

Can you double check this one... doesn't seem like anything has been changed:

Screenshot 2023-09-12 at 10 37 36 AM

**Comment by zacharykeeping** [comment]
Hey @tiagov8 

    > Can you double check this one... doesn't seem like anything has been changed:

This just adds "/" to the end. It seems like "/tom" redirects to Tom B, whereas "/tom/" ensures it goes to Tom I. Perhaps there's another issue here as well...

**Comment by tiagov8** [comment]
> Hey @tiagov8
> 
> > Can you double check this one... doesn't seem like anything has been changed:
> 
> This just adds "/" to the end. It seems like "/tom" redirects to Tom B, whereas "/tom/" ensures it goes to Tom I. Perhaps there's another issue here as well...

Hey @zacharykeeping 

This is a bug 🐛 that needs fixing... 

The slash shouldn't point to different URLs

- [ ] 1. Please create an Issue on SSW.People repository to fix
- [ ] 2. Update the Acknowledgement link to be https://ssw.com.au/people/tom-bui/ so it's not dependant on the above

**Comment by zacharykeeping** [comment]
Hey @tiagov8 

> * [ ]  1. Please create an Issue on SSW.People repository to fix

Looks like Brady's already raised this issue here: https://github.com/SSWConsulting/SSW.People/issues/534

> * [ ]  2. Update the Acknowledgement link to be https://ssw.com.au/people/tom-bui/ so it's not dependant on the above

Done - this is already fixed in this PR. It should be pointing to Tom I, which is /tom/, but it's currently redirecting to /tom-bui/.

**Comment by GordonBeeming** [comment]
FYI, at around 36 hours old the bot will ping again in the PR... this isn't a bug, we changed the duration and that unfortunately means that there will be a 2nd ping in this PR

**Comment by zacharykeeping** [comment]
Closing as the rule no longer exists.

**Comment by tiagov8** [comment]
> Closing as the rule no longer exists.

Hey @zacharykeeping 

What's the context? How does the rule no longer exists?

**Comment by zacharykeeping** [comment]
> > Closing as the rule no longer exists.
> 
> Hey @zacharykeeping
> 
> What's the context? How does the rule no longer exists?

Hey @tiagov8 

Looks like it was removed here: https://github.com/SSWConsulting/SSW.Rules.Content/pull/6684

There doesn't appear to be any other current rules using the "/tom" acknowledgement either.

**Comment by GordonBeeming** [comment]
@YazhiChen We should never delete rules (or web content/assets in general) without a redirect. 

If a rule isn't valid any longer, we should archive it with a link to the new rule

**Pull request closed without merging**
