### PR TITLE
Create Rule “useful-information-on-changes/rule”

### PR DESCRIPTION
**Pull request by tiagov8**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by wicksipedia** [comment]
@tiagov8 I think that screenshots of anonymized bad/good PR descriptions would be better... thoughts?

**Comment by wicksipedia** [comment]
@tiagov8 IMHO a good PR usually includes a demonstration of the change e.g. a screenshot to show that text/UI has been changed or a Done video to demo functionality change. Consider adding it to the rule

**Comment by tiagov8** [comment]
> @tiagov8 IMHO a good PR usually includes a demonstration of the change e.g. a screenshot to show that text/UI has been changed or a Done video to demo functionality change. Consider adding it to the rule

done - added at the end

**Comment by tiagov8** [comment]
> @tiagov8 I think that screenshots of anonymized bad/good PR descriptions would be better... thoughts?

Visually I agree, but...
Generally screenshots are bad for maintenance (say we want to change the text in the examples)
I also think the generic text makes it work for PBIs/Issues/Tasks on different environments not just GitHub

**Review by adamcogan — APPROVED** [review]

**Pull request merged**
