### PR TITLE
Updated intro to follow CTF "different-types-of-testing"

### PR DESCRIPTION
**Pull request by tiagov8**

### CODE REVIEW

**Review by Hona — CHANGES_REQUESTED** [review]
This removed the important emphasis that testing is to reduce risk.

**Review by GordonBeeming — APPROVED** [review]
LGTM

**Comment by GordonBeeming** [comment]
@Hona good point 😅

**Review by adamcogan — APPROVED** [review]

**Comment by tiagov8** [comment]
> This removed the important emphasis that testing is to reduce risk.

Added

**Review by adamcogan — APPROVED** [review]

**Comment by tiagov8** [comment]
Hey @Hona 

I don't know how you did this review, but after adding the sentence back and getting an approval from Adam we still can't get the PR merged because you requested a change

**Comment by Hona** [comment]
Hey @tiagov8 you can 'dismiss' a review that you have actioned if the original reviewer has not reapproved:

image
Figure: Dismiss a review

**Comment by tiagov8** [comment]
Hey @Hona 

Noted. I knew about dismissing, but it doesn't seem the right thing... I expected a way to say it was actioned.

**Pull request merged**
