### PR TITLE
XS✔ ◾ Update 'zz' rule to include 'yy'

### PR DESCRIPTION
**Pull request by jeoffreyfischer**
**Tip: Use [SSW Rule Writer GPT](https://chat.openai.com/g/g-cOvrRzEnU-ssw-rules-writer) for help with writing rules 🤖**
>
> 1. What triggered this change? (PBI link, Email Subject, conversation + reason, etc)

✏️A conversation with Adam

> 2. What was changed?

✏️The content of the grey box about using less aggressive 'zz' was moved to a new section. It was also clearly specified that this is called a 'yy'.

> 3. Did you do pair or mob programming (list names)?

✏️No

### CODE REVIEW

**Review by adamcogan — APPROVED** [review]

**Review by adamcogan — APPROVED** [review]

**Comment by tiagov8** [comment]
Hey @bradystroud 

"Resolve conflicts" button is disabled for me.

- [ ] 1. Please have a look and get this one through ;)

**Comment by JackDevAU** [comment]
Seems @Ben0189 got his changes in first. https://github.com/SSWConsulting/SSW.Rules.Content/pull/7677

He changed the rule name so this folder (this rule) doesn't exist anymore. 

for the quickest update to this rule - close this PR and make changes again to the new rule `zz-files`

**Review by JackDevAU — CHANGES_REQUESTED** [review]
See my last comment

**Comment by jeoffreyfischer** [comment]
Hey @JackDevAU 

✅ Done - see the link to the new PR: https://github.com/SSWConsulting/SSW.Rules.Content/pull/7715

**Comment by jeoffreyfischer** [comment]
This PR was closed as it was modified by @Ben0189 on a different branch.
Link to new PR: https://github.com/SSWConsulting/SSW.Rules.Content/pull/7715

**Comment by JackDevAU** [comment]
Hey @tiagov8, 

This was due to merge conflicts that couldn't be solved automatically. (Due to Bens PR moving the rule, updating content) - it was just easier to create a new PR

**Pull request closed without merging**
