### PR TITLE
Create Rule “oxford-comma/rule”

### PR DESCRIPTION
**Pull request by leehawkinsssw**
Automatically generated by Netlify CMS

### CODE REVIEW

**Review by tiagov8 — CHANGES_REQUESTED** [review]
Hi Lee,

I am not clear about this content... we normally show a preference on SSW Rules but this seems more like a curiosity article.

The examples are confusing... a bad example on using it + a good example on using it

If we don't have a recommendation I don't think we need a SSW rule... Agree?

**Review by adamcogan — APPROVED** [review]

**Comment by adamcogan** [comment]
Some people say 'always use an Oxford comma'

Some people - mostly older - say they hate it and they never use it.

This rule says to me, know when you must have it... and it's clutter to use it unnecessarily.

-a

**Comment by leehawkinsssw** [comment]
Are you happy to merge this one now, Tiago, or do you still have concerns?

**Comment by tiagov8** [comment]
> Are you happy to merge this one now, Tiago, or do you still have concerns?

Approved by @adamcogan , so I guess it's good to go

**Pull request merged**
