### PR TITLE
Update rules-to-better-designers.md

### PR DESCRIPTION
**Pull request by 2fernandez**
Adding rule to category

### CODE REVIEW

**Review by UlyssesMaclaren — CHANGES_REQUESTED** [review]
change it to:

what-is-figma

**Comment by UlyssesMaclaren** [comment]
Short URLs FTW!!











Ulysses Maclaren   |   SSW General Manager<http://www.ssw.com.au/People/Ulysses-Maclaren?utm_source=emailsignature>   |    +61 419 418 232<https://www.ssw.com.au/ssw/Company/Offices/?utm_source=emailsignature>   |   Ping me on ***@***.***>

**Review by 2fernandez — COMMENTED** [review]
@UlyssesMaclaren san, URL updated.

**Comment by jaydenalchin** [comment]
> UlyssesMaclaren san, URL updated.

Hi @2fernandez 

1. The URL needs to be updated on the rule itself as well
2. This seems to overlap with software-for-ux-design in the same category. Consider adding this content to that rule and reframing this rule as "Do you know the basics of Figma?" listing some core concepts and user guidelines?

**Review by bradystroud — APPROVED** [review]

**Comment by 2fernandez** [comment]
hi @jaydenalchin , 

> 1. The URL needs to be updated on the rule itself as well
Done


> 2. This seems to overlap with software-for-ux-design in the same category. Consider adding this content to that rule and reframing this rule as "Do you know the basics of Figma?" listing some core concepts and user guidelines?

Good catch - I think this should be a separate rule mainly because:

**software-for-ux-design more** - I see this as a high-level rule that precedes this rule. 
**what-is-figma** - I would like to mainly highlight "why" a developer or a development team should use Figma

**what-is-figma** - I agree that the URL and the title should be something better, such as "Top 5 reasons to use Figma". 
**what-is-figma** - The intention is to draw the user to the top reasons "why" they should be using figma.

1. Do you have any suggestions as to renaming this article that highlights the top uses of "Figma"?

**Comment by jaydenalchin** [comment]
> software-for-ux-design more - I see this as a high-level rule that precedes this rule.
what-is-figma - The intention is to draw the user to the top reasons "why" they should be using figma.
> I would like to mainly highlight "why" a developer or a development team should use Figma
Do you have any suggestions as to renaming this article that highlights the top uses of "Figma"?

With the context above, I would rename this "Do you know Figma's 5 flagship features?" / figma-flagship-features (fun alliteration).

In this case I think a nice way to differentiate the two rules is _why_ vs _what_. Then we can make more rules that dig into the _how_ of each feature in detail. A category for Figma practices would be very cool! 

For context - the rule software-for-ux-design was written when we moved from Sketch to Figma, explaining why we should use Figma over other tools + why we should still use other Adobe tools in their niches. This is why I felt both these rules are trying to say very similar things.

**Comment by 2fernandez** [comment]
thanks Jayden, 
I've improved on that slightly based to "Do you know Figma's top 5 uses"

**Review by 2fernandez — COMMENTED** [review]
please review new URL

**Comment by 2fernandez** [comment]
Done ! in this other PR with Tiago 
https://github.com/SSWConsulting/SSW.Rules.Content/pull/6299

**Pull request closed without merging**
