### PR TITLE
Update Rule “automated-test-code-first-class-citizen/rule”

### PR DESCRIPTION
**Pull request by leehawkinsssw**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by leehawkinsssw** [comment]
Hi @tiagov8 Please revert the title of this rule, your changed title doesn't read well

**Comment by tiagov8** [comment]
> Hi @tiagov8 Please revert the title of this rule, your changed title doesn't read well

Hey @leehawkinsssw 
Please suggest a title that follow the standard "Do you..."

**Comment by leehawkinsssw** [comment]
> > Hi @tiagov8 Please revert the title of this rule, your changed title doesn't read well
> 
> Hey @leehawkinsssw Please suggest a title that follow the standard "Do you..."

"Do you treat your automated test code as a first-class citizen?"

**Comment by tiagov8** [comment]
> Do you treat your automated test code as a first-class citizen?

done - https://github.com/SSWConsulting/SSW.Rules.Content/pull/4408

**Pull request merged**
